### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Gaming4LifeDE** [invoiceninja/admin-portal#413]
The desktop app is currently being distributed as a snap. Many users (myself included) prefer flatpak. Will there be a flatpak version of the desktop app? Could be uploaded to flathub

**Comment by Gaming4LifeDE** [comment]
I'm not too sure actually, maybe this would help?

https://www.reddit.com/r/flatpak/comments/mnh5dd/any_examples_of_building_a_flutter_20_app_with/?utm_medium=android_app&utm_source=share

**Comment by nekohayo** [comment]
Personally I've been using [Epiphany](https://wiki.gnome.org/Apps/Web)'s ["web app" feature](https://help.gnome.org/users/epiphany/stable/browse-webapps.html.en) to use `https://app.invoiceninja.com/time_tracker?q=Ftime_tracker` as an "app", so to speak, but I've been worried that maybe with v5 this wouldn't work the same anymore (?), if so a flatpak would be the way to go, because snaps really aren't a thing on anything but Ubuntu anyway.

**Comment by 12people** [comment]
@hillelcoren Actually, that issue is for compiling the Flutter app locally, but Flutter apps can already be distributed via Flatpak as compiled binaries. There are [a number](https://flathub.org/apps/details/ca.hamaluik.Timecop) [of projects](https://flathub.org/apps/details/com.enjoyingfoss.feeel) [on Flathub](https://flathub.org/apps/details/im.fluffychat.Fluffychat) [already](https://flathub.org/apps/details/io.github.prateekmedia.pstube) [doing](https://flathub.org/apps/details/com.github.KRTirtho.Spotube) [that](https://flathub.org/apps/details/com.enjoyingfoss.Parlera).

You can look at the flatpak manifests for each of the projects linked to above by clicking "See details" under the "Publisher" heading.

And here's a more general example: https://github.com/Merrit/flutter_flatpak_example

**Comment by TriggerDingus** [comment]
It doesn't appear the there are any technial obstacles left to a Flatpak package, at least since late last year or early this year. Has a Flatpak package been sidelined? If not, when might it be available?

**Comment by hillelcoren** [comment]
Sorry, we aren't able to provide timeframes for future features. 

If you're a developer we'd gladly accept a pull request.

**Comment by hillelcoren** [comment]
FYI... https://github.com/flathub/flathub/pull/4659

**Comment by hillelcoren** [comment]
https://flathub.org/apps/com.invoiceninja.InvoiceNinja

**Comment by TriggerDingus** [comment]
Nice!!
