### ISSUE TITLE
Expenses don't show tax in invoices

### ISSUE THREAD

**Issue by thirstyice** [invoiceninja/admin-portal#675]
## Setup
- Version: v5.10.10
- Environment: ZIP

## Interface
- Flutter: [x]
- React: [x]
- Both: [x]

## Checklist
- [x] Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
- [x] Have you searched existing issues?
- [x] Have you reported this to Slack/forum before posting?
- [x] Have you inspected the logs in storage/logs/laravel.log for any errors? (no errors)

## Describe the bug
Forum post: https://forum.invoiceninja.com/t/expenses-with-tax-dont-show-tax-in-invoices/16576
When I add an expense with tax to an invoice, it doesn’t show the “Tax” column in the product table. If I add a product with tax then the column is shown correctly, including the correct values for the expenses.

See forum post for more info

### Steps To Reproduce
Invoice an expense w/ tax

### Expected Behavior
Tax column to be shown

**Comment by hillelcoren** [comment]
Can you please post a screenshot of your company tax settings?

**Comment by thirstyice** [comment]
Here you go:
![image](https://github.com/user-attachments/assets/c3c4bda6-abf4-4d9c-8a72-f491751f9b0d)

**Comment by hillelcoren** [comment]
@turbo124 I'm able to reproduce this issue in the Flutter app and not the React app.

In the Flutter app the line_item.type_id is being set to 6 to track that it's an expense, but this is preventing the tax from being shown. The React app sets the type_id to 1 so appears to work correctly.

Since the expense_id field is set maybe the type_id == 6 can be removed, do you use it in the backend?

**Comment by turbo124** [comment]
@hillelcoren this type can be removed. I am using it in only one spot, but can easily change it with no impact.

**Comment by hillelcoren** [comment]
Sounds good, I'll remove it from the AP
